name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # python_version:
        #   # - "3.7.1"
        #   # - "3.8"
        #   # - "3.9"
        #   # - "3.10"
        # os:
        #   # - "ubuntu"
        # container_app:
        #   # - docker

        include:
          - os: macos
            container-app: podman
            python_version: "3.7.1"

    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash -l {0}

    concurrency:
      group: ci-${{ matrix.os }}-${{ matrix.python_version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    - name: Install sed
      if: ${{ matrix.os == 'macos' }}
      run: brew install gnu-sed

    - name: Prepare .env file
      run: touch .env

    - name: Prepare conda environment (osx)
      if: ${{ matrix.os == 'macos' }}
      run: |
        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
        sed -i s/python\ 3\.7\.1/python\ ${{ matrix.python_version }}/ conda/dev.yaml
        cat conda/dev.yaml

    - name: Prepare conda environment (linux)
      if: ${{ matrix.os == 'ubuntu' }}
      run: |
        sed -i s/python\ 3\.7\.1/python\ ${{ matrix.python_version }}/ conda/dev.yaml
        cat conda/dev.yaml

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        environment-file: conda/${{ matrix.container_app }}.yaml
        channels: conda-forge,nodefaults
        activate-environment: containers-sugar
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install podman
      if: ${{ matrix.container_app == 'podman' }}
      run: sed -i s/docker-compose/podman-compose/ .containers-sugar.yaml

    - name: Install dependencies
      run: poetry install

    - name: run unit tests
      run: makim tests

    - name: CLI tests
      run: |
        containers-sugar help
        containers-sugar version
        containers-sugar build --group group1 --services ""
        containers-sugar build --group group2 --services ""
        containers-sugar build --group group1

    - name: Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v3

    - name: Run style checks
      if: success() || failure()
      run: |
        pre-commit install
        makim lint
